version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  node:
    build: .
    container_name: node-app
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGODB_URL=mongodb://mongo:27017/blogdb
      - PORT=8000

volumes:
  mongo-data:
